---
- hosts: linux
  roles:
    - role: setenv_01_local
    - role: initial_01_basesetup
    - role: initial_02_services
    - role: initial_03_hardware
    - role: initial_04_baseusers
    - role: initial_05_network
    - role: setenv_02_statistics
    